!Create Printpattern.py
codehouseindia/Python-Programs pull request #13
Opened 2020-09-30 19:51 UTC by kunjikatripathi

added printing program

2020-10-01 17:15 UTC, ashishaaashu commented on Printpattern.py
> +                print("*",end=" ")
if n == False:
         for i in range(row,0,-1):
            print("\n",end=" ")
            for j in range(1,i+1):
                print("*", end=" ")
else:
    print("Invalid!!")

2020-10-01 17:16 UTC, ashishaaashu requested changes

2020-10-01 17:16 UTC, ashishaaashu commented on Printpattern.py
> +                print("*",end=" ")
missing code from ur program

2020-10-01 17:19 UTC, kunjikatripathi commented
Yup!! that's missing . thankx

2020-10-04 18:51 UTC, kunjikatripathi commented
#https://www.facebook.com/100005198139377/posts/1502511503265440/
#subscribe by code house
 #codehouse merged this pull request also

2020-10-04 19:32 UTC, kunjikatripathi commented
#https://www.facebook.com/100005198139377/posts/1502511503265440/
#subscribe by code house
#codehouse merged this pull request also

2020-10-05 06:01 UTC, merged

2020-10-05 06:01 UTC, codehouseindia commented
Merged